name: MSBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  SOLUTION_FILE_PATH: .

  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        platform: ["x64", "x86"]
        configuration: ["Debug", "Release"]

    steps:
    - uses: actions/checkout@v3

    # WiX projects have to use x86 and cpp projects have to use Win32, so make the latter available as VS_PLATFORM
    - name: Override VS_PLATFORM for x86 -> Win32
      run: |
        echo "VS_PLATFORM=Win32" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
      shell: pwsh
      if: matrix.platform == 'x86'

    - name: Override VS_PLATFORM for x64 -> x64
      run: |
        echo "VS_PLATFORM=x64" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
      shell: pwsh
      if: matrix.platform == 'x64'

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{matrix.configuration}} /p:Platform=${{matrix.platform}} ${{env.SOLUTION_FILE_PATH}}

    - name: Locate VSTest
      uses: benstaniford/Setup-VSTest@v1
      id: setup_vstest

    - name: Run VSTest
      id: run_vstest
      working-directory: ${{env.VS_PLATFORM}}\${{matrix.configuration}}\
      run: vstest.console.exe /Platform:${{matrix.platform}} .\DummyServiceLibTests.dll

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: DummyInstaller-${{matrix.configuration}}-${{matrix.platform}}.msi
        path: DummyInstaller/bin/${{matrix.platform}}/${{matrix.configuration}}/DummyInstaller.msi

